### ISSUE TITLE
Won't run on Linux

### ISSUE THREAD

**Issue by rabywastaken** [g-rock84/mine_mod_updater#1]
Am I doing something wrong, or is this supposed not to run on linux? I'm using ZorinOS btw :v

import-im6.q16: not authorized `os' @ error/constitute.c/WriteImage/1037.
from: can't read /var/mail/platform
import-im6.q16: not authorized `re' @ error/constitute.c/WriteImage/1037.
import-im6.q16: not authorized `requests' @ error/constitute.c/WriteImage/1037.
import-im6.q16: not authorized `zipfile' @ error/constitute.c/WriteImage/1037.
import-im6.q16: not authorized `json' @ error/constitute.c/WriteImage/1037.
from: can't read /var/mail/collections
from: can't read /var/mail/PyQt5
import-im6.q16: not authorized `cgitb' @ error/constitute.c/WriteImage/1037.
./mod_updater_ui_Mk1.py: line 10: syntax error near unexpected token `format'
./mod_updater_ui_Mk1.py: line 10: `cgitb.enable(format = 'text')'

**Comment by g-rock84** [comment]
Whoo! First issue! How did you start the program? Depending on how you executed it might explain what the problem is.

**Comment by rabywastaken** [comment]
Hold up, let me download it again...
There we go, same issue again, I enabled permission to execute, and executed on the terminal using `./mod_updater_ui_Mk1.py`
![Screenshot from 2020-08-25 14-01-59](https://user-images.githubusercontent.com/31973406/91177605-df7da080-e6db-11ea-97a4-4bd7b95a5b10.png)

**Comment by Amcio** [comment]
The script has no shebang line.
try executing with `$ python3 mod_updater_ui_Mk1.py`

**Comment by rabywastaken** [comment]
oh! That worked :v
It still doesn't update tho... When I click on update, or check for update, it does nothing.
![Screenshot from 2020-08-26 02-37-08](https://user-images.githubusercontent.com/31973406/91244809-31a6dc00-e745-11ea-8940-11a73b5e5d12.png)

**Comment by g-rock84** [comment]
Ah yes, the program is not feature complete just yet. Once it is, I will compile a binary that you can run without python installed on the system. For now, it just tries to identify the mods in the given mod folder. I am working on the update function as we speak. Though, it super cool to see it working (mostly) on linux! I hadn't tested it on linux yet. So, thanks for the feedback!

I noticed that the program failed to ID 33 mods. That seems like a lot of mods it couldn't find. It would be super awesome if you could post that list. I can use it to make the identifying process better. Assuming you downloaded most of them from CurseForge that is.
